"""Tests for the AgentRegistry client (offline / no chain connection)."""

import hashlib
import json
import os
from pathlib import Path

import pytest
from pycardano import Address, Network, PlutusV3Script, ScriptHash, script_hash

from vector_agent.registry import AgentRegistry, _derive_nft_name
from vector_agent.plutus_data import OutputReference


# Path to the blueprint generated by aiken build
BLUEPRINT_PATH = (
    Path(__file__).parent.parent.parent
    / "contracts"
    / "agent-registry"
    / "plutus.json"
)


class TestFromBlueprint:
    """Test loading the registry from the Plutus blueprint."""

    @pytest.fixture
    def registry(self) -> AgentRegistry:
        return AgentRegistry.from_blueprint(str(BLUEPRINT_PATH), network="testnet")

    def test_loads_without_error(self, registry):
        assert registry is not None

    def test_policy_id_is_56_hex_chars(self, registry):
        pid = registry.policy_id_hex
        assert len(pid) == 56
        # Must be valid hex
        bytes.fromhex(pid)

    def test_policy_id_matches_blueprint(self, registry):
        with open(BLUEPRINT_PATH) as f:
            bp = json.load(f)
        expected = bp["validators"][0]["hash"]
        assert registry.policy_id_hex == expected

    def test_script_address_is_testnet(self, registry):
        addr = registry.script_address
        assert isinstance(addr, Address)
        # Testnet addresses start with "addr_test1"
        addr_str = addr.encode()
        assert addr_str.startswith("addr_test1")

    def test_mainnet_address(self):
        reg = AgentRegistry.from_blueprint(str(BLUEPRINT_PATH), network="mainnet")
        addr_str = reg.script_address.encode()
        assert addr_str.startswith("addr1")


class TestDeriveNftName:
    """Test the NFT name derivation matches the on-chain logic."""

    def test_deterministic(self):
        seed = OutputReference(transaction_id=b"\xde" * 32, output_index=0)
        name1 = _derive_nft_name(seed)
        name2 = _derive_nft_name(seed)
        assert name1 == name2

    def test_is_32_bytes(self):
        seed = OutputReference(transaction_id=b"\xab" * 32, output_index=0)
        name = _derive_nft_name(seed)
        assert len(name) == 32

    def test_different_seeds_different_names(self):
        seed1 = OutputReference(transaction_id=b"\xab" * 32, output_index=0)
        seed2 = OutputReference(transaction_id=b"\xab" * 32, output_index=1)
        assert _derive_nft_name(seed1) != _derive_nft_name(seed2)

    def test_uses_blake2b_256(self):
        seed = OutputReference(transaction_id=b"\xde" * 32, output_index=0)
        cbor_bytes = seed.to_cbor()
        expected = hashlib.blake2b(cbor_bytes, digest_size=32).digest()
        assert _derive_nft_name(seed) == expected


class TestNotConnected:
    """Test that operations fail gracefully when not connected."""

    @pytest.fixture
    def registry(self) -> AgentRegistry:
        return AgentRegistry.from_blueprint(str(BLUEPRINT_PATH))

    def test_query_raises_without_connection(self, registry):
        with pytest.raises(RuntimeError, match="Not connected"):
            registry.query_agents()

    def test_context_raises_without_connection(self, registry):
        with pytest.raises(RuntimeError, match="Not connected"):
            _ = registry.context
