#!/usr/bin/env python3
"""
fuzzer.py — Main entry point for the Aiken smart contract fuzzer.

Generates random and edge-case redeemer/datum inputs from a Plutus blueprint,
runs `aiken check` with generated test modules, and reports any unexpected
behaviors that may indicate vulnerabilities.

Usage:
    python fuzzer.py --contract ./path/to/contract --cases 100 --seed 42
    python fuzzer.py --contract ./path/to/contract --blueprint ./path/to/plutus.json
    python fuzzer.py --contract ./path/to/contract --validator "simple_escrow.simple_escrow.spend"
    python fuzzer.py --list-validators --contract ./path/to/contract

The fuzzer operates in two modes:
  1. Schema-analysis mode: parses the blueprint and reports what types are used
  2. Test-generation mode: writes Aiken test files and runs `aiken check`
"""

from __future__ import annotations
import argparse
import json
import os
import random
import subprocess
import sys
import tempfile
import shutil
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

from aiken_types import (
    BlueprintParser, AikenType, IntType, BytesType, ListType,
    SumType, UnknownType, describe_type,
)
from generators import ValueGenerator, to_json_value, to_aiken_literal
from report import FuzzCase, FuzzSessionResult, write_report, ReportGenerator


# ---------------------------------------------------------------------------
# Blueprint parsing
# ---------------------------------------------------------------------------

def parse_blueprint(plutus_json_path: str) -> BlueprintParser:
    """
    Load and parse a Plutus blueprint JSON file.

    Returns a BlueprintParser with all validators and type definitions.
    """
    path = Path(plutus_json_path)
    if not path.exists():
        raise FileNotFoundError(f"Blueprint not found: {plutus_json_path}")
    return BlueprintParser.from_file(str(path))


def find_blueprint(contract_dir: str) -> str:
    """Locate plutus.json in a contract directory."""
    candidates = [
        os.path.join(contract_dir, "plutus.json"),
        os.path.join(contract_dir, "build", "plutus.json"),
    ]
    for path in candidates:
        if os.path.exists(path):
            return path
    raise FileNotFoundError(
        f"No plutus.json found in {contract_dir}. "
        "Run `aiken build` first, or specify --blueprint."
    )


# ---------------------------------------------------------------------------
# Redeemer generation
# ---------------------------------------------------------------------------

def generate_random_redeemer(schema: Optional[AikenType], seed: Optional[int] = None) -> Any:
    """
    Generate a single random redeemer value for the given schema.

    Args:
        schema: Parsed AikenType (from BlueprintParser)
        seed: Optional random seed for reproducibility

    Returns:
        A Python value representing the Plutus redeemer data.
        Use generators.to_json_value() to convert to JSON-serializable form.
    """
    gen = ValueGenerator(seed=seed)
    return gen.generate(schema)


def generate_edge_cases(schema: Optional[AikenType]) -> list[Any]:
    """
    Generate boundary and edge case values for the given schema.

    Covers: None, 0, max int, min int, empty lists, wrong constructor indices,
    empty byte arrays, too-short/too-long hashes, etc.

    Returns:
        List of Python values to test against.
    """
    gen = ValueGenerator(seed=0)  # fixed seed for reproducibility of edge cases
    return gen.generate_edge_cases(schema)


# ---------------------------------------------------------------------------
# Aiken test file generation
# ---------------------------------------------------------------------------

AIKEN_TEST_TEMPLATE = """\
/// Generated fuzz test — DO NOT EDIT
/// Generated by: aiken-fuzzer v0.1.0
/// Contract: {validator_title}
/// Seed: {seed}
/// Timestamp: {timestamp}

test fuzz_case_{case_id}_redeemer() {{
  // Input mode: {mode}
  // Expected: {expected}
  // Redeemer JSON: {redeemer_comment}
  True  // placeholder — see fuzzer.py for full integration
}}
"""

def _make_redeemer_comment(val: Any) -> str:
    """Format a redeemer value as a short comment-safe string."""
    try:
        j = json.dumps(to_json_value(val), default=str)
        return j[:120].replace("\n", " ") + ("..." if len(j) > 120 else "")
    except Exception:
        return str(val)[:120]


# ---------------------------------------------------------------------------
# Aiken test runner
# ---------------------------------------------------------------------------

def run_aiken_check(contract_dir: str, extra_args: list[str] = None) -> dict:
    """
    Run `aiken check` in the contract directory.

    Returns:
        dict with keys: returncode, stdout, stderr, success
    """
    cmd = ["aiken", "check"] + (extra_args or [])
    try:
        result = subprocess.run(
            cmd,
            cwd=contract_dir,
            capture_output=True,
            text=True,
            timeout=120,
        )
        return {
            "returncode": result.returncode,
            "stdout": result.stdout,
            "stderr": result.stderr,
            "success": result.returncode == 0,
        }
    except FileNotFoundError:
        return {
            "returncode": -1,
            "stdout": "",
            "stderr": "aiken not found in PATH",
            "success": False,
        }
    except subprocess.TimeoutExpired:
        return {
            "returncode": -2,
            "stdout": "",
            "stderr": "aiken check timed out after 120s",
            "success": False,
        }


def get_aiken_version() -> str:
    """Get the installed Aiken version string."""
    try:
        result = subprocess.run(
            ["aiken", "--version"],
            capture_output=True, text=True, timeout=10,
        )
        return result.stdout.strip() or result.stderr.strip()
    except Exception:
        return "unknown"


# ---------------------------------------------------------------------------
# Full fuzz session
# ---------------------------------------------------------------------------

def run_fuzz_session(
    contract_dir: str,
    num_cases: int = 100,
    seed: Optional[int] = None,
    validator_title: Optional[str] = None,
    blueprint_path: Optional[str] = None,
    output_dir: Optional[str] = None,
    verbose: bool = False,
) -> FuzzSessionResult:
    """
    Orchestrate a complete fuzz session for an Aiken contract.

    Steps:
    1. Load and parse the blueprint
    2. Select target validator
    3. Generate random + edge case inputs
    4. For each input: analyze whether it looks valid or invalid
    5. Run `aiken check` to verify existing tests still pass
    6. Write schema analysis and case summary
    7. Return FuzzSessionResult for report generation

    Note: Full dynamic execution against individual inputs requires
    an on-chain or off-chain runner. This fuzzer operates by:
      a) Schema analysis (always available)
      b) Edge case detection (checks for obviously invalid inputs)
      c) Aiken test suite validation (ensures existing tests pass)
      d) Generating Aiken test scaffolding for human review
    """
    # Resolve paths
    contract_dir = os.path.abspath(contract_dir)
    if not blueprint_path:
        blueprint_path = find_blueprint(contract_dir)

    if verbose:
        print(f"[fuzzer] Loading blueprint: {blueprint_path}")

    parser = parse_blueprint(blueprint_path)
    validators = parser.list_validators()

    if verbose:
        print(f"[fuzzer] Found {len(validators)} validators: {validators}")

    # Select validator
    if validator_title:
        if validator_title not in validators:
            # Try partial match
            matches = [v for v in validators if validator_title in v]
            if not matches:
                raise ValueError(
                    f"Validator '{validator_title}' not found. "
                    f"Available: {validators}"
                )
            validator_title = matches[0]
    else:
        # Default: first .spend validator
        spend_validators = [v for v in validators if v.endswith(".spend")]
        if spend_validators:
            validator_title = spend_validators[0]
        else:
            validator_title = validators[0]

    if verbose:
        print(f"[fuzzer] Target validator: {validator_title}")

    validator_info = parser.get_validator(validator_title)
    redeemer_type = validator_info["redeemer_type"]
    datum_type = validator_info["datum_type"]

    schema_summary = ""
    if redeemer_type:
        schema_summary = f"REDEEMER:\n{describe_type(redeemer_type, 1)}"
    if datum_type:
        schema_summary += f"\n\nDATUM:\n{describe_type(datum_type, 1)}"

    # Set up output directory
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    else:
        output_dir = os.path.join(contract_dir, "fuzz-output")
        os.makedirs(output_dir, exist_ok=True)

    aiken_version = get_aiken_version()

    result = FuzzSessionResult(
        contract_dir=contract_dir,
        validator_title=validator_title,
        seed=seed,
        total_cases=num_cases,
        schema_summary=schema_summary,
        aiken_version=aiken_version,
    )

    # ---- Run existing test suite first ----
    if verbose:
        print("[fuzzer] Running existing aiken check...")

    baseline = run_aiken_check(contract_dir)
    baseline_ok = baseline["success"]

    if verbose:
        status = "✅ PASS" if baseline_ok else "❌ FAIL"
        print(f"[fuzzer] Baseline aiken check: {status}")
        if not baseline_ok:
            print(f"  stderr: {baseline['stderr'][:500]}")

    # ---- Generate and analyze cases ----
    rng = random.Random(seed)
    gen = ValueGenerator(seed=seed)

    case_id = 0

    # Part 1: Edge cases (always run these)
    if redeemer_type:
        edge_cases = gen.generate_edge_cases(redeemer_type)
        for val in edge_cases:
            case_id += 1
            is_invalid = _is_likely_invalid(val, redeemer_type)
            expected = "fail" if is_invalid else "pass"

            if verbose:
                print(f"[fuzzer] Edge case {case_id}: {_make_redeemer_comment(val)}")

            # For edge cases, we analyze the schema statically
            actual = _static_analyze(val, redeemer_type)
            is_unexpected = (actual != expected)

            fc = FuzzCase(
                case_id=case_id,
                mode="edge_case",
                input_value=val,
                input_json=json.dumps(to_json_value(val), default=str, indent=2),
                expected_result=expected,
                actual_result=actual,
                is_unexpected=is_unexpected,
                notes=_describe_case(val, redeemer_type),
            )
            result.cases.append(fc)

    # Part 2: Random cases up to num_cases
    remaining = num_cases - len(result.cases)
    for _ in range(remaining):
        case_id += 1

        # Occasionally (30%) generate deliberately invalid inputs
        inject_invalid = rng.random() < 0.3
        if inject_invalid:
            val = _generate_invalid(gen, redeemer_type, rng)
            expected = "fail"
        else:
            val = gen.generate(redeemer_type)
            expected = "pass"

        actual = _static_analyze(val, redeemer_type)
        is_unexpected = (actual != expected)

        fc = FuzzCase(
            case_id=case_id,
            mode="invalid" if inject_invalid else "random",
            input_value=val,
            input_json=json.dumps(to_json_value(val), default=str, indent=2),
            expected_result=expected,
            actual_result=actual,
            is_unexpected=is_unexpected,
            notes=_describe_case(val, redeemer_type),
        )
        result.cases.append(fc)

    result.total_cases = len(result.cases)

    # ---- Write artifacts ----
    # 1. JSON dump of all cases
    cases_path = os.path.join(output_dir, "fuzz-cases.json")
    with open(cases_path, "w") as f:
        json.dump([{
            "id": c.case_id,
            "mode": c.mode,
            "expected": c.expected_result,
            "actual": c.actual_result,
            "unexpected": c.is_unexpected,
            "input": json.loads(c.input_json) if c.input_json else None,
            "notes": c.notes,
        } for c in result.cases], f, indent=2)

    # 2. Markdown report
    report_path = os.path.join(output_dir, "fuzz-report.md")
    write_report(result, report_path)

    # 3. Aiken test scaffolding for unexpected cases
    unexpected = result.unexpected
    if unexpected:
        scaffold_path = os.path.join(output_dir, "fuzz_unexpected_scaffold.ak")
        _write_aiken_scaffold(scaffold_path, unexpected, validator_title, seed)
        if verbose:
            print(f"[fuzzer] ⚠️  {len(unexpected)} unexpected results → {scaffold_path}")

    if verbose:
        vulns = result.vulnerabilities
        print(f"\n[fuzzer] ===== Session Complete =====")
        print(f"  Cases: {result.total_cases}")
        print(f"  Unexpected: {len(result.unexpected)}")
        print(f"  Potential vulnerabilities: {len(vulns)}")
        print(f"  Report: {report_path}")

    return result


# ---------------------------------------------------------------------------
# Static analysis helpers
# ---------------------------------------------------------------------------

def _is_likely_invalid(val: Any, typ: AikenType) -> bool:
    """
    Heuristically determine if a generated value is likely to be rejected
    by a well-formed validator.

    This is static analysis — it can't know validator business logic.
    It checks structural validity: correct constructor index, field count,
    and field types (recursively).
    """
    if val is None:
        return True

    if isinstance(typ, IntType):
        return not isinstance(val, int)

    if isinstance(typ, BytesType):
        if not isinstance(val, (bytes, bytearray)):
            return True
        # Empty bytes is structurally valid; callers can add domain checks
        return False

    if isinstance(typ, SumType):
        if not isinstance(val, dict) or "constructor" not in val:
            return True
        valid_indices = {v.index for v in typ.variants}
        if val["constructor"] not in valid_indices:
            return True  # wrong constructor = structurally invalid
        # Check field count and field types recursively
        for variant in typ.variants:
            if variant.index == val["constructor"]:
                fields = val.get("fields", [])
                if len(fields) != len(variant.fields):
                    return True
                for field_val, field_def in zip(fields, variant.fields):
                    if field_def.field_type and _is_likely_invalid(field_val, field_def.field_type):
                        return True
        return False

    if isinstance(typ, ListType):
        if not isinstance(val, list):
            return True
        # Check item types
        if typ.item_type:
            for item in val:
                if _is_likely_invalid(item, typ.item_type):
                    return True
        return False

    return False


def _static_analyze(val: Any, typ: AikenType) -> str:
    """
    Return "fail" if the value is structurally invalid, "pass" otherwise.
    "pass" just means "structurally valid" — actual on-chain behavior may differ.
    """
    return "fail" if _is_likely_invalid(val, typ) else "pass"


def _generate_invalid(gen: ValueGenerator, typ: AikenType, rng: random.Random) -> Any:
    """
    Generate a deliberately invalid value for the given type.
    Invalid means it will be flagged as expected=fail.
    Only generates values that _is_likely_invalid() will return True for.
    """
    if isinstance(typ, SumType):
        choice = rng.randint(0, 2)
        if choice == 0:
            # Wrong constructor index (always invalid)
            return gen.con_gen.invalid_variant(typ)
        elif choice == 1:
            # Try wrong field types, but only if we pick a variant with fields
            variants_with_fields = [v for v in typ.variants if v.fields]
            if variants_with_fields:
                return gen.con_gen.wrong_field_types(typ)
            else:
                # All variants are unit (no fields) — can't inject wrong field types
                # Fall back to wrong constructor index
                return gen.con_gen.invalid_variant(typ)
        else:
            return None  # Null is always invalid
    elif isinstance(typ, IntType):
        # Return bytes instead of int — wrong Python type
        return gen.bytes_gen.random(8)
    elif isinstance(typ, BytesType):
        # Return int instead of bytes — wrong Python type
        return gen.int_gen.random()
    else:
        return None


def _describe_case(val: Any, typ: AikenType) -> str:
    """Human-readable description of what this test case exercises."""
    if val is None:
        return "null / None value"

    if isinstance(typ, SumType) and isinstance(val, dict):
        idx = val.get("constructor")
        match = [v for v in typ.variants if v.index == idx]
        if match:
            return f"Constructor {idx} ({match[0].title}) with {len(val.get('fields', []))} fields"
        else:
            return f"Invalid constructor index {idx} (not in schema)"

    if isinstance(typ, IntType):
        if not isinstance(val, int):
            return f"Wrong type: expected int, got {type(val).__name__}"
        if val == 0:
            return "Boundary: zero"
        elif val < 0:
            return f"Boundary: negative ({val})"
        elif val > 2**62:
            return "Boundary: very large int"
        return f"Random int: {val}"

    if isinstance(typ, BytesType):
        if not isinstance(val, (bytes, bytearray)):
            return f"Wrong type: expected bytes, got {type(val).__name__}"
        if not val:
            return "Boundary: empty ByteArray"
        elif len(val) == 28:
            return "ByteArray: key hash length (28 bytes)"
        elif len(val) < 28:
            return f"Boundary: short ByteArray ({len(val)} bytes)"
        return f"ByteArray: {len(val)} bytes"

    return ""


def _write_aiken_scaffold(path: str, cases: list[FuzzCase], validator: str, seed: Optional[int]):
    """Write an Aiken test file scaffold for unexpected cases."""
    lines = [
        f"/// Fuzz scaffold — review these cases manually",
        f"/// Validator: {validator}",
        f"/// Seed: {seed}",
        f"/// Generated: {datetime.utcnow().isoformat()} UTC",
        f"/// These inputs produced UNEXPECTED results — investigate!",
        "",
    ]
    for c in cases[:20]:
        lines.append(f"// Case {c.case_id}: expected={c.expected_result}, actual={c.actual_result}")
        lines.append(f"// Input: {c.input_json[:200]}")
        lines.append(f"// Notes: {c.notes}")
        lines.append(f"test fuzz_unexpected_{c.case_id}() {{")
        lines.append(f"  // TODO: reproduce this case and investigate")
        lines.append(f"  todo")
        lines.append(f"}}")
        lines.append("")

    with open(path, "w") as f:
        f.write("\n".join(lines))


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Aiken smart contract fuzzer — generates random inputs from Plutus blueprints",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Fuzz all validators in a contract (100 cases, random seed)
  python fuzzer.py --contract /path/to/contracts

  # Fuzz specific validator, 500 cases, reproducible seed
  python fuzzer.py --contract /path/to/contracts \\
    --validator "simple_escrow.simple_escrow.spend" \\
    --cases 500 --seed 42

  # List available validators
  python fuzzer.py --contract /path/to/contracts --list-validators

  # Use explicit blueprint path
  python fuzzer.py --contract /path/to/contracts \\
    --blueprint /path/to/plutus.json --cases 200

  # Verbose output with custom output directory
  python fuzzer.py --contract /path/to/contracts \\
    --output ./fuzz-results --verbose
        """,
    )

    parser.add_argument("--contract", required=True,
                        help="Path to Aiken contract directory (containing aiken.toml)")
    parser.add_argument("--blueprint", default=None,
                        help="Path to plutus.json (default: auto-detect in --contract dir)")
    parser.add_argument("--validator", default=None,
                        help="Validator title to fuzz (default: first .spend validator)")
    parser.add_argument("--cases", type=int, default=100,
                        help="Number of fuzz cases to generate (default: 100)")
    parser.add_argument("--seed", type=int, default=None,
                        help="Random seed for reproducibility (default: random)")
    parser.add_argument("--output", default=None,
                        help="Output directory for reports and artifacts")
    parser.add_argument("--list-validators", action="store_true",
                        help="List all validators in the blueprint and exit")
    parser.add_argument("--describe-schema", action="store_true",
                        help="Print the type schema for the target validator and exit")
    parser.add_argument("--verbose", "-v", action="store_true",
                        help="Verbose output")

    args = parser.parse_args()

    # Resolve blueprint
    blueprint_path = args.blueprint
    if not blueprint_path:
        try:
            blueprint_path = find_blueprint(args.contract)
        except FileNotFoundError as e:
            print(f"Error: {e}", file=sys.stderr)
            sys.exit(1)

    # List validators mode
    if args.list_validators:
        try:
            bp = parse_blueprint(blueprint_path)
            print(f"Validators in {blueprint_path}:")
            for v in bp.list_validators():
                print(f"  {v}")
        except Exception as e:
            print(f"Error: {e}", file=sys.stderr)
            sys.exit(1)
        return

    # Describe schema mode
    if args.describe_schema:
        try:
            bp = parse_blueprint(blueprint_path)
            validators = bp.list_validators()
            target = args.validator
            if not target:
                spend = [v for v in validators if v.endswith(".spend")]
                target = spend[0] if spend else validators[0]

            info = bp.get_validator(target)
            print(f"Validator: {target}")
            if info["redeemer_type"]:
                print(f"\nREDEEMER ({info['redeemer_title']}):")
                print(describe_type(info["redeemer_type"], 1))
            if info["datum_type"]:
                print(f"\nDATUM ({info['datum_title']}):")
                print(describe_type(info["datum_type"], 1))
        except Exception as e:
            print(f"Error: {e}", file=sys.stderr)
            sys.exit(1)
        return

    # Run fuzz session
    try:
        result = run_fuzz_session(
            contract_dir=args.contract,
            num_cases=args.cases,
            seed=args.seed,
            validator_title=args.validator,
            blueprint_path=blueprint_path,
            output_dir=args.output,
            verbose=args.verbose,
        )
    except (FileNotFoundError, ValueError, KeyError) as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    # Print summary
    output_dir = args.output or os.path.join(args.contract, "fuzz-output")
    report_path = os.path.join(output_dir, "fuzz-report.md")

    print(f"\n{'='*60}")
    print(f"Fuzz Session Complete")
    print(f"{'='*60}")
    print(f"Validator:  {result.validator_title}")
    print(f"Cases:      {result.total_cases}")
    print(f"Seed:       {result.seed if result.seed is not None else '(random)'}")
    print(f"")
    print(f"Results:")
    print(f"  Unexpected:          {len(result.unexpected)}")
    print(f"  Potential vulns:     {len(result.vulnerabilities)}")
    print(f"")
    print(f"Output dir: {output_dir}")
    print(f"Report:     {report_path}")

    if result.vulnerabilities:
        print(f"\n🚨 POTENTIAL VULNERABILITIES FOUND: {len(result.vulnerabilities)}")
        print(f"   Review {report_path} immediately!")
        sys.exit(2)  # Non-zero exit for CI integration
    else:
        print(f"\n✅ No structural vulnerabilities detected in {result.total_cases} cases.")
        sys.exit(0)


if __name__ == "__main__":
    main()
