"""
AgentRegistry client — builds and submits registration, update, and
deregistration transactions against the Vector Agent Registry contract.

Uses PyCardano with an Ogmios backend for chain interaction.

Usage:
    from vector_agent.registry import AgentRegistry

    registry = AgentRegistry.from_blueprint("path/to/plutus.json", network="testnet")
    registry.connect_ogmios("ogmios.vector.testnet.apexfusion.org", port=443, secure=True)

    tx_hash = registry.register(payment_skey, agent_datum)
    tx_hash = registry.update(payment_skey, agent_utxo, new_datum)
    tx_hash = registry.deregister(payment_skey, agent_utxo)
"""

from __future__ import annotations

import hashlib
import json
import logging
import time
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Tuple

from pycardano import (
    Address,
    MultiAsset,
    Asset,
    AssetName,
    Network,
    PaymentSigningKey,
    PaymentVerificationKey,
    PlutusV3Script,
    Redeemer,
    ScriptHash,
    TransactionBuilder,
    TransactionId,
    TransactionInput,
    TransactionOutput,
    UTxO,
    Value,
    script_hash,
)
from pycardano.backend.ogmios_v6 import OgmiosChainContext
from pycardano.serialization import IndefiniteList, RawCBOR

from vector_agent.models import MIN_AP3X_DEPOSIT_DFM, AgentProfile
from vector_agent.plutus_data import (
    AgentDatum,
    BurnRedeemer,
    DeregisterRedeemer,
    OutputReference,
    RegisterRedeemer,
    UpdateRedeemer,
    VerificationKeyCredential,
)

logger = logging.getLogger(__name__)


@dataclass
class RegistryConfig:
    """Runtime configuration for the registry client."""
    script: PlutusV3Script
    policy_id: ScriptHash
    script_address: Address
    network: Network


class AgentRegistry:
    """
    High-level client for the Vector Agent Registry smart contract.

    Handles:
    - Loading the compiled Plutus script from blueprint
    - Connecting to the chain via Ogmios
    - Building register / update / deregister transactions
    - Querying registered agents
    """

    def __init__(self, config: RegistryConfig):
        self._config = config
        self._context: Optional[OgmiosChainContext] = None

    # ──────────────────────────────────────────────────────────────────
    # Factory
    # ──────────────────────────────────────────────────────────────────

    @classmethod
    def from_blueprint(
        cls,
        blueprint_path: str,
        network: str = "testnet",
    ) -> "AgentRegistry":
        """
        Create an AgentRegistry from a Plutus blueprint JSON file.

        Args:
            blueprint_path: Path to plutus.json generated by `aiken build`.
            network: "testnet" or "mainnet".

        Returns:
            Configured AgentRegistry instance (not yet connected to chain).
        """
        path = Path(blueprint_path)
        with open(path) as f:
            blueprint = json.load(f)

        # All validators in the multi-validator share the same compiled code
        compiled_hex = blueprint["validators"][0]["compiledCode"]
        expected_hash = blueprint["validators"][0]["hash"]

        script = PlutusV3Script(bytes.fromhex(compiled_hex))
        pid = script_hash(script)

        # Verify hash matches the blueprint
        actual_hash = pid.payload.hex()
        if actual_hash != expected_hash:
            raise ValueError(
                f"Script hash mismatch: blueprint says {expected_hash}, "
                f"computed {actual_hash}"
            )

        net = Network.TESTNET if network == "testnet" else Network.MAINNET
        script_addr = Address(payment_part=pid, network=net)

        config = RegistryConfig(
            script=script,
            policy_id=pid,
            script_address=script_addr,
            network=net,
        )

        logger.info(
            "Loaded registry script: hash=%s, address=%s",
            actual_hash,
            script_addr.to_primitive(),
        )
        return cls(config)

    # ──────────────────────────────────────────────────────────────────
    # Connection
    # ──────────────────────────────────────────────────────────────────

    def connect_ogmios(
        self,
        host: str = "ogmios.vector.testnet.apexfusion.org",
        port: int = 443,
        secure: bool = True,
    ) -> None:
        """
        Connect to the chain via Ogmios WebSocket.

        Args:
            host: Ogmios hostname.
            port: Ogmios port (443 for HTTPS/WSS).
            secure: Use WSS (True for HTTPS endpoints).
        """
        self._context = OgmiosChainContext(
            host=host,
            port=port,
            secure=secure,
            network=self._config.network,
        )
        logger.info("Connected to Ogmios at %s:%d (secure=%s)", host, port, secure)

    @property
    def context(self) -> OgmiosChainContext:
        if self._context is None:
            raise RuntimeError(
                "Not connected to chain. Call connect_ogmios() first."
            )
        return self._context

    # ──────────────────────────────────────────────────────────────────
    # Queries
    # ──────────────────────────────────────────────────────────────────

    def query_agents(self) -> List[Tuple[UTxO, AgentDatum]]:
        """
        Query all agent UTxOs at the registry script address.

        Returns:
            List of (UTxO, AgentDatum) tuples for all registered agents.
        """
        utxos = self.context.utxos(self._config.script_address)
        results = []
        for utxo in utxos:
            if utxo.output.datum is not None:
                try:
                    datum = _parse_datum(utxo.output.datum)
                    if datum is not None:
                        results.append((utxo, datum))
                except Exception as e:
                    logger.warning("Failed to parse datum at %s: %s", utxo.input, e)
        return results

    def find_agent_utxo(
        self,
        nft_asset_name: bytes,
    ) -> Optional[Tuple[UTxO, AgentDatum]]:
        """
        Find a specific agent's UTxO by its identity NFT asset name.

        Args:
            nft_asset_name: The 32-byte NFT asset name (raw bytes).

        Returns:
            (UTxO, AgentDatum) if found, None otherwise.
        """
        for utxo, datum in self.query_agents():
            value = utxo.output.amount
            if isinstance(value, Value) and value.multi_asset:
                pid = self._config.policy_id
                if pid in value.multi_asset:
                    tokens = value.multi_asset[pid]
                    if AssetName(nft_asset_name) in tokens:
                        return utxo, datum
        return None

    # ──────────────────────────────────────────────────────────────────
    # Transaction builders
    # ──────────────────────────────────────────────────────────────────

    def register(
        self,
        payment_skey: PaymentSigningKey,
        owner_vkh: bytes,
        name: str,
        description: str,
        capabilities: List[str],
        framework: str,
        endpoint: str,
        change_address: Address,
        collateral_utxo: UTxO,
        seed_utxo: Optional[UTxO] = None,
    ) -> str:
        """
        Register a new agent on-chain.

        Builds a transaction that:
        1. Consumes a seed UTxO (for unique NFT name derivation)
        2. Mints 1 identity NFT
        3. Creates output at script address with inline datum + NFT + ≥10 AP3X

        Args:
            payment_skey: Signing key for the owner.
            owner_vkh: 28-byte verification key hash of the owner.
            name: Agent name.
            description: Agent description.
            capabilities: List of capability tags.
            framework: Framework identifier.
            endpoint: A2A endpoint URL.
            change_address: Address for change output.
            collateral_utxo: UTxO for script collateral.
            seed_utxo: UTxO to consume as seed. If None, picks one from wallet.

        Returns:
            Transaction hash (hex string).
        """
        ctx = self.context
        config = self._config

        # If no seed UTxO provided, pick the first available one at change_address
        if seed_utxo is None or collateral_utxo is None:
            wallet_utxos = ctx.utxos(change_address)
            if not wallet_utxos:
                raise ValueError("No UTxOs available at change address")
            if seed_utxo is None:
                seed_utxo = wallet_utxos[0]
            if collateral_utxo is None:
                # Use the last UTxO as collateral (different from seed if possible)
                collateral_utxo = wallet_utxos[-1]

        # Derive NFT asset name = blake2b_256(CBOR(OutputReference))
        seed_ref = OutputReference(
            transaction_id=bytes(seed_utxo.input.transaction_id),
            output_index=seed_utxo.input.index,
        )
        nft_name_bytes = _derive_nft_name(seed_ref)
        asset_name = AssetName(nft_name_bytes)

        # Build datum
        datum = AgentDatum(
            owner=VerificationKeyCredential(owner_vkh),
            name=name.encode("utf-8"),
            description=description.encode("utf-8"),
            capabilities=IndefiniteList([cap.encode("utf-8") for cap in capabilities]),
            framework=framework.encode("utf-8"),
            endpoint=endpoint.encode("utf-8"),
            registered_at=int(time.time() * 1000),
        )

        # Build redeemer
        mint_redeemer = Redeemer(RegisterRedeemer(seed=seed_ref))

        # Build transaction
        builder = TransactionBuilder(ctx)
        builder.add_input(seed_utxo)

        # Mint 1 NFT
        builder.add_minting_script(config.script, redeemer=mint_redeemer)
        builder.mint = MultiAsset({config.policy_id: Asset({asset_name: 1})})

        # Output at script address with inline datum, NFT, and min deposit
        script_output = TransactionOutput(
            config.script_address,
            amount=Value(
                MIN_AP3X_DEPOSIT_DFM,
                MultiAsset({config.policy_id: Asset({asset_name: 1})}),
            ),
            datum=datum,
        )
        builder.add_output(script_output)

        # Allow the builder to select wallet UTxOs for fee coverage
        builder.add_input_address(change_address)

        # Collateral and required signer
        builder.collaterals.append(collateral_utxo)
        builder.required_signers = [
            PaymentVerificationKey.from_signing_key(payment_skey).hash()
        ]

        # Build, sign, submit
        signed_tx = builder.build_and_sign(
            signing_keys=[payment_skey],
            change_address=change_address,
        )

        tx_hash = signed_tx.id.payload.hex()
        ctx.submit_tx_cbor(signed_tx.to_cbor())
        logger.info(
            "Registered agent '%s' — tx: %s, nft: %s",
            name, tx_hash, nft_name_bytes.hex(),
        )
        return tx_hash

    def update(
        self,
        payment_skey: PaymentSigningKey,
        agent_utxo: UTxO,
        name: Optional[str] = None,
        description: Optional[str] = None,
        capabilities: Optional[List[str]] = None,
        framework: Optional[str] = None,
        endpoint: Optional[str] = None,
        change_address: Optional[Address] = None,
        collateral_utxo: Optional[UTxO] = None,
    ) -> str:
        """
        Update an existing agent's profile.

        Spends the current agent UTxO and creates a new one with
        updated datum fields. Fields set to None are preserved.

        Args:
            payment_skey: Signing key for the owner.
            agent_utxo: The current agent UTxO to spend.
            name: New name (or None to keep existing).
            description: New description (or None to keep existing).
            capabilities: New capabilities (or None to keep existing).
            framework: New framework (or None to keep existing).
            endpoint: New endpoint (or None to keep existing).
            change_address: Address for change output.
            collateral_utxo: UTxO for script collateral.

        Returns:
            Transaction hash (hex string).
        """
        ctx = self.context
        config = self._config

        # Parse existing datum (handles both RawCBOR and PlutusData)
        existing_datum = _parse_datum(agent_utxo.output.datum)
        if existing_datum is None:
            raise ValueError("Could not parse existing agent datum")

        # Merge fields
        new_datum = AgentDatum(
            owner=existing_datum.owner,
            name=name.encode("utf-8") if name else existing_datum.name,
            description=(
                description.encode("utf-8") if description else existing_datum.description
            ),
            capabilities=(
                IndefiniteList([c.encode("utf-8") for c in capabilities])
                if capabilities
                else existing_datum.capabilities
            ),
            framework=framework.encode("utf-8") if framework else existing_datum.framework,
            endpoint=endpoint.encode("utf-8") if endpoint else existing_datum.endpoint,
            registered_at=existing_datum.registered_at,
        )

        # Determine change address from signer
        vk = PaymentVerificationKey.from_signing_key(payment_skey)
        if change_address is None:
            change_address = Address(payment_part=vk.hash(), network=config.network)

        # Get collateral if not provided
        if collateral_utxo is None:
            wallet_utxos = ctx.utxos(change_address)
            if not wallet_utxos:
                raise ValueError("No UTxOs for collateral at change address")
            collateral_utxo = wallet_utxos[0]

        # Build transaction
        spend_redeemer = Redeemer(UpdateRedeemer())
        builder = TransactionBuilder(ctx)
        builder.add_script_input(
            utxo=agent_utxo,
            script=config.script,
            datum=None,  # Inline datum — read from UTxO
            redeemer=spend_redeemer,
        )

        # Continuing output with same value and updated datum
        builder.add_output(TransactionOutput(
            config.script_address,
            amount=agent_utxo.output.amount,
            datum=new_datum,
        ))

        # Allow the builder to select wallet UTxOs for fee coverage
        builder.add_input_address(change_address)

        builder.collaterals.append(collateral_utxo)
        builder.required_signers = [vk.hash()]

        signed_tx = builder.build_and_sign(
            signing_keys=[payment_skey],
            change_address=change_address,
        )

        tx_hash = signed_tx.id.payload.hex()
        ctx.submit_tx_cbor(signed_tx.to_cbor())
        logger.info("Updated agent — tx: %s", tx_hash)
        return tx_hash

    def deregister(
        self,
        payment_skey: PaymentSigningKey,
        agent_utxo: UTxO,
        change_address: Optional[Address] = None,
        collateral_utxo: Optional[UTxO] = None,
    ) -> str:
        """
        Deregister an agent — spend UTxO + burn identity NFT.

        The AP3X deposit is returned to the change address.

        Args:
            payment_skey: Signing key for the owner.
            agent_utxo: The agent UTxO to deregister.
            change_address: Address for change + deposit return.
            collateral_utxo: UTxO for script collateral.

        Returns:
            Transaction hash (hex string).
        """
        ctx = self.context
        config = self._config

        vk = PaymentVerificationKey.from_signing_key(payment_skey)
        if change_address is None:
            change_address = Address(payment_part=vk.hash(), network=config.network)

        if collateral_utxo is None:
            wallet_utxos = ctx.utxos(change_address)
            if not wallet_utxos:
                raise ValueError("No UTxOs for collateral at change address")
            collateral_utxo = wallet_utxos[0]

        # Find the NFT asset name in the agent UTxO
        nft_asset_name = _find_nft_in_utxo(agent_utxo, config.policy_id)
        if nft_asset_name is None:
            raise ValueError("No identity NFT found in agent UTxO")

        # Spend redeemer: Deregister
        spend_redeemer = Redeemer(DeregisterRedeemer())

        # Mint redeemer: Burn
        burn_redeemer = Redeemer(BurnRedeemer())

        builder = TransactionBuilder(ctx)

        # Spend the agent UTxO
        builder.add_script_input(
            utxo=agent_utxo,
            script=config.script,
            datum=None,  # Inline datum
            redeemer=spend_redeemer,
        )

        # Burn the NFT
        builder.add_minting_script(config.script, redeemer=burn_redeemer)
        builder.mint = MultiAsset({config.policy_id: Asset({nft_asset_name: -1})})

        # Allow the builder to select wallet UTxOs for fee coverage
        builder.add_input_address(change_address)

        builder.collaterals.append(collateral_utxo)
        builder.required_signers = [vk.hash()]

        signed_tx = builder.build_and_sign(
            signing_keys=[payment_skey],
            change_address=change_address,
        )

        tx_hash = signed_tx.id.payload.hex()
        ctx.submit_tx_cbor(signed_tx.to_cbor())
        logger.info("Deregistered agent — tx: %s", tx_hash)
        return tx_hash

    # ──────────────────────────────────────────────────────────────────
    # Convenience
    # ──────────────────────────────────────────────────────────────────

    @property
    def policy_id_hex(self) -> str:
        """Hex-encoded policy ID / script hash."""
        return self._config.policy_id.payload.hex()

    @property
    def script_address(self) -> Address:
        """The registry script address."""
        return self._config.script_address

    def to_agent_profile(self, utxo: UTxO, datum: AgentDatum) -> AgentProfile:
        """Convert a UTxO + datum pair to an AgentProfile model."""
        # Find NFT name
        nft_name_asset = _find_nft_in_utxo(utxo, self._config.policy_id)
        nft_hex = nft_name_asset.payload.hex() if nft_name_asset else None

        # Extract owner vkh
        owner_hex = ""
        if hasattr(datum.owner, "vkey_hash"):
            owner_hex = datum.owner.vkey_hash.hex()

        utxo_ref = f"{utxo.input.transaction_id.payload.hex()}#{utxo.input.index}"

        return AgentProfile(
            owner=owner_hex,
            name=datum.name.decode("utf-8"),
            description=datum.description.decode("utf-8"),
            capabilities=[
                c.decode("utf-8") if isinstance(c, bytes) else str(c)
                for c in datum.capabilities
            ],
            framework=datum.framework.decode("utf-8"),
            endpoint=datum.endpoint.decode("utf-8"),
            registered_at=datum.registered_at,
            utxo_ref=utxo_ref,
            nft_asset_name=nft_hex,
            policy_id=self.policy_id_hex,
        )


# ──────────────────────────────────────────────────────────────────────
# Private helpers
# ──────────────────────────────────────────────────────────────────────


def _derive_nft_name(seed_ref: OutputReference) -> bytes:
    """
    Derive the NFT asset name from a seed OutputReference.

    Must match the on-chain logic: blake2b_256(cbor.serialise(seed_utxo_ref)).
    We use the CBOR serialization of our PlutusData OutputReference.
    """
    cbor_bytes = seed_ref.to_cbor()
    return hashlib.blake2b(cbor_bytes, digest_size=32).digest()


def _parse_datum(raw_datum) -> Optional[AgentDatum]:
    """
    Parse an AgentDatum from a UTxO datum, handling both PlutusData and RawCBOR.

    Ogmios may return inline datums as RawCBOR objects (raw CBOR bytes)
    rather than parsed PlutusData. This helper handles both cases.
    """
    if isinstance(raw_datum, RawCBOR):
        return AgentDatum.from_cbor(raw_datum.cbor)
    elif hasattr(raw_datum, "to_primitive"):
        return AgentDatum.from_primitive(raw_datum.to_primitive())
    else:
        logger.warning("Unknown datum type: %s", type(raw_datum))
        return None


def _find_nft_in_utxo(utxo: UTxO, policy_id: ScriptHash) -> Optional[AssetName]:
    """Find the identity NFT asset name in a UTxO's value."""
    value = utxo.output.amount
    if isinstance(value, Value) and value.multi_asset:
        if policy_id in value.multi_asset:
            tokens = value.multi_asset[policy_id]
            for asset_name in tokens:
                if tokens[asset_name] == 1:
                    return asset_name
    return None
